# Generated by Django 2.2 on 2020-09-03 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinjam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('nim', models.TextField(default='')),
                ('judulbuku', models.TextField(default='')),
                ('tgl_masuk', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
