# Generated by Django 2.2 on 2020-09-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinjam',
            name='judulbuku',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pinjam',
            name='nim',
            field=models.CharField(max_length=100),
        ),
    ]
