# Generated by Django 2.2 on 2020-09-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mhs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mhs', models.CharField(max_length=255)),
                ('nim', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('notelp', models.IntegerField(default=0)),
                ('alamat', models.TextField(default='')),
            ],
        ),
    ]
