# Generated by Django 2.2 on 2020-09-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mhs',
            old_name='mhs',
            new_name='nama',
        ),
        migrations.RenameField(
            model_name='mhs',
            old_name='notelp',
            new_name='telp',
        ),
    ]
