# Generated by Django 2.2 on 2020-09-15 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_kegiatan', models.DateField(default=datetime.datetime.now)),
                ('judul', models.CharField(max_length=100)),
                ('ket', models.TextField(max_length=200)),
                ('upload_img', models.ImageField(default='', upload_to='images/')),
            ],
        ),
    ]
