# Generated by Django 2.2 on 2020-09-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penulis', models.TextField(default='')),
                ('judul', models.TextField(default='')),
                ('pnb', models.TextField(default='')),
                ('isbn', models.IntegerField(default=0)),
                ('des', models.TextField(default='')),
            ],
        ),
    ]
