# Generated by Django 2.2 on 2020-09-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='des',
            new_name='desc',
        ),
    ]
