# Generated by Django 2.2 on 2020-09-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_pinjam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pinjam',
        ),
    ]
