# Generated by Django 2.2 on 2020-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_delete_pinjam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='judul',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='penulis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='pnb',
            field=models.CharField(max_length=255),
        ),
    ]
