# Generated by Django 2.2.13 on 2020-09-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('alamat', models.TextField(default='')),
                ('deskripsi', models.TextField(default='')),
                ('pic', models.CharField(max_length=255)),
                ('telp', models.IntegerField(default='')),
            ],
        ),
    ]
